AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Course application using AWS SAM CLI

Globals:
  Function:
    Timeout: 3
    Runtime: nodejs14.x
    CodeUri: dist/

Resources:
  AddCourseFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: addCourse.handler
      Events:
        AddCourse:
          Type: Api
          Properties:
            Path: /course/add
            Method: post

  UpdateCourseFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: updateCourse.handler
      Events:
        AddCourse:
          Type: Api
          Properties:
            Path: /course/update/{id}
            Method: put

  GetAllCoursesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: getAllCourses.handler
      Events:
        AddCourse:
          Type: Api
          Properties:
            Path: /courses
            Method: get

  GetCourseFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: getCourse.handler
      Events:
        AddCourse:
          Type: Api
          Properties:
            Path: /course/{id}
            Method: get

  DeleteCourseFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: deleteCourse.handler
      Events:
        AddCourse:
          Type: Api
          Properties:
            Path: /course/delete/{id}
            Method: delete
